sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run-script test-travis
after_success:
  - npm run semantic-release
  - npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"

