language: node_js
node_js:
  - "0.10"
  - "0.12"
matrix:
  allow_failures:
    - node_js: "0.12"
  fast_finish: true
script: "npm run-script test-travis"
after_script: "npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"
